### ISSUE TITLE
[疑] 七溜八溜，无拆福州。

### ISSUE THREAD

**Issue by ztl8702** [MindongLab/foochow-idioms#30]
`七溜八溜，无拆福州。` 的 `拆` 有疑问。

**Comment by Guanchishan** [comment]
拆释为[比得上](https://github.com/MindongLab/foochow-idioms-data/blob/master/other%20idioms.tsv#L5)

民间也有“无离”的写法，连读读音很接近。关键看民间有无读阳去（即离）的，若有视为变种收入？

**Comment by Guanchishan** [comment]
鄙意目前可以直接結案，未來開發大衆錄音後再伺機解決。
