### ISSUE TITLE
[新] 道士摇铃铃，蜀侬保蜀身

### ISSUE THREAD

**Issue by ztl8702** [MindongLab/foochow-idioms#48]
![image](https://user-images.githubusercontent.com/2714446/32935712-3dc6fa4a-cbac-11e7-988a-a5c086b9060b.png)

Source:
陈泽平李如龙字典p188

Recommended by [davidzdh](https://zh.wikipedia.org/wiki/User:Davidzdh)

**Comment by Guanchishan** [comment]
Done
