### ISSUE TITLE
[新] 大頭魺賣西瓜，賣來賣去maa成花

### ISSUE THREAD

**Issue by Guanchishan** [MindongLab/foochow-idioms#49]
![image](https://user-images.githubusercontent.com/30859354/33086964-3c766498-cf24-11e7-81f4-f44c626115d0.png)
陳澤平李如龍詞典

**Comment by Mizuumihama** [comment]
一點疑問，這是“謠”，打油詩，算在福州話熟語裏面嗎？

**Comment by Mizuumihama** [comment]
一點疑問，這是“謠”，打油詩，算在福州話熟語裏面嗎？

**Comment by ztl8702** [comment]
> 一點疑問，這是“謠”，打油詩，算在福州話熟語裏面嗎？

我也不清楚。我觉得这个分类是次要的，反正是福州话口头常用的表达都收。见 #64

**Comment by Guanchishan** [comment]
HHS94原文暂且收录入FoochowIdiomData了。
