### ISSUE TITLE
[新] 礱礱粟，粟礱礱，糠養猪，米養儂

### ISSUE THREAD

**Issue by Guanchishan** [MindongLab/foochow-idioms#54]
![image](https://user-images.githubusercontent.com/30859354/33526111-a40bc390-d876-11e7-861c-d3d234529241.png)
《福州方言词典》1994年10月福建人民出版社 第55頁

**Comment by ztl8702** [comment]
这个其实在《福州方言俗语歌谣》里面有。《俗语歌谣》整部的“歌谣”部分我当时都略去了。现在可以补上。

**Comment by Guanchishan** [comment]
HHS94的原句暂且录于FoochowIdiomData了。
