### ISSUE TITLE
[新] 點點篤篤，桃花李落，小人君子，底儂到此，拍糞齪

### ISSUE THREAD

**Issue by Guanchishan** [MindongLab/foochow-idioms#55]
![image](https://user-images.githubusercontent.com/30859354/33526149-a0c37b8c-d877-11e7-9d6a-364f3f42a805.png)
![image](https://user-images.githubusercontent.com/30859354/33526154-a82c0074-d877-11e7-89f0-cb526d0a2a29.png)
HHS94 p66

**Comment by ztl8702** [comment]
这个很有意思。“点点滴滴”的福州话版。

**Comment by Guanchishan** [comment]
君子 何老师好像说 gung2 ziu3/4？数字是实用字典采用的音调

**Comment by Guanchishan** [comment]
HHS94的说法已收录于FoochowIdiomData
