### ISSUE TITLE
[新] 藕cyeung蔗laa

### ISSUE THREAD

**Issue by Guanchishan** [MindongLab/foochow-idioms#65]
![image](https://user-images.githubusercontent.com/30859354/33776633-00774c58-dc7d-11e7-9a33-f7947f4c306c.png)
HHS94. p44.

**Comment by ztl8702** [comment]
题外话。我现在觉得去录这本字典里面的例句应该也蛮有意义。

**Comment by Guanchishan** [comment]
全體例句的話工作量太大了吧，不過確實地道句子ia laa，極具鑒賞收藏價值。總之以所謂的俗語爲中核慢慢展開收錄工作吧，反正鄭君你前面不也提到，你得到詞典作者許可，可以錄入了來著。

**Comment by Guanchishan** [comment]
Done
