### ISSUE TITLE
[新] 毛毛雞，假大格

### ISSUE THREAD

**Issue by Guanchishan** [MindongLab/foochow-idioms#68]
![image](https://user-images.githubusercontent.com/30859354/34070366-fabd68d2-e29f-11e7-8fc8-7ca75f59f561.png)
HHS94. p82.

**Comment by ztl8702** [comment]
已有： http://idioms.mindong.asia/#/idiom/%E6%AF%9B%E6%AF%9B%E9%B8%A1%E2%80%94%E2%80%94%E5%81%87%E5%A4%A7%E6%A0%BC%E3%80%82

不过可以添加新的出处和解释。
