### ISSUE TITLE
拗九二月二，凡种都落地

### ISSUE THREAD

**Issue by Guanchishan** [MindongLab/foochow-idioms#73]
葉余，是一位連江人：

『拗九二月二，凡种都落地』
/ao1 ao4 ni1 uo1 nei5 , huong3 zyng3 du1 lou4 dei5/
这是本地的一条农谚，在正月二十九到二月初二这段时间，一些农作物就可以适时播种了。

这条谚语需要用本地方言念读才押韵。

**Comment by Guanchishan** [comment]
@siuze 凡字读音能确定是huang还是huong否？

**Comment by siuze** [comment]
拗九前字我们这里并没有脱落u，仍读作au。凡是我记录有误，应为“逢”hung

**Comment by Guanchishan** [comment]
Done
