### ISSUE TITLE
暗蜂镇虼蝲

### ISSUE THREAD

**Issue by Guanchishan** [MindongLab/foochow-idioms#86]
【福州话与语文】“暗蜂镇虼蝲（gala）”，虼蝲即蟑螂。暗蜂见过，纤长细腰，泛着蓝紫光；但镇虼蝲却没有亲见，只听说虼蝲在暗蜂面前，神志不清，任其摆布，直至留下残骸一堆。为此我查了资料，方知“暗蜂”的学名是扁头泥蜂。雌蜂在产卵时会寻找蟑螂，并将其作为幼虫的食物。扁头泥蜂向蟑螂注射毒液，从而操控蟑螂的大脑乃至身体活动，使其成为傀儡。被操控的蟑螂仍然活着，但已经身不由己。它会跟随扁头泥蜂的指示，进入到它挖好的洞穴中静静待着，毫无反抗。而扁头泥蜂会在蟑螂的身上产下一枚卵。扁头泥蜂的幼虫会以蟑螂的身体内脏血肉为食，在其体内成长并结茧孵化，最后从蟑螂已经成为空壳的身体里钻出来，留下一具被掏空的尸体。蟑螂有“小强”之称，被泥蜂所镇，所言“一物降一物”也。有丈夫，在外亦强，专治别人，回家却被老婆治。悍妻，暗蜂也。扁头泥蜂所施毒液能控制蟑螂意念，莫非真有迷幻药？

https://m.weibo.cn/status/4279024458534640

**Comment by ztl8702** [comment]
http://idioms.mindong.asia/#/idiom/%E6%9A%97%E8%9C%82%E5%8F%AE%E5%AE%B6%E8%9C%A1%E3%80%82

**Comment by Guanchishan** [comment]
当时没有检索到，可能我用错关键词，疏忽了。不知未来的新网站有无搜索俗字上的优化（手动哭笑不得表情）

**Comment by Guanchishan** [comment]
置入StoriaDiHokchew了。新设计了一个idiom字段来匹配俗语。OK的话就close了。
